// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../engine/entities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function DeleteConnection(id: number): $CancellablePromise<void> {
    return $Call.ByID(629468635, id);
}

export function GetConnections(): $CancellablePromise<types$0.Connection[] | null> {
    return $Call.ByID(3875144445);
}

export function UpdateConnection(config: entities$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(761924589, config);
}
