// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../engine/entities/models.js";

export function Connect(config: entities$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(1396630503, config);
}

export function Disconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(3910241401, connID);
}

export function ExecuteQuery(connID: string, rawQuery: string): $CancellablePromise<entities$0.QueryResult | null> {
    return $Call.ByID(2057292634, connID, rawQuery);
}

export function GetQueryHistory(limit: number, since: string): $CancellablePromise<db$0.QueryHistoryEntity[] | null> {
    return $Call.ByID(2140042053, limit, since);
}

export function InspectDatabase(connID: string): $CancellablePromise<entities$0.InspectTableInfo[] | null> {
    return $Call.ByID(2574358800, connID);
}
