// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../engine/entities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function Connect(config: entities$0.ConnectionConfig): $CancellablePromise<boolean> {
    return $Call.ByID(1396630503, config);
}

export function Disconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(3910241401, connID);
}

export function ExecuteQuery(queryInput: entities$0.QueryInput): $CancellablePromise<entities$0.QueryResult | null> {
    return $Call.ByID(2057292634, queryInput);
}

export function GetActiveConnection(): $CancellablePromise<string> {
    return $Call.ByID(123274639);
}

export function GetActiveConnectionObject(): $CancellablePromise<[types$0.Connection, boolean]> {
    return $Call.ByID(1493165516);
}

export function GetQueryHistory(limit: number, since: string): $CancellablePromise<db$0.QueryHistoryEntity[] | null> {
    return $Call.ByID(2140042053, limit, since);
}

export function InspectDatabase(): $CancellablePromise<entities$0.InspectTableInfo[] | null> {
    return $Call.ByID(2574358800);
}

export function PingConfig(config: entities$0.ConnectionConfig): $CancellablePromise<boolean> {
    return $Call.ByID(2383367173, config);
}

export function PingConnection(connID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1640356639, connID);
}

export function SaveAndConnect(config: entities$0.ConnectionConfig): $CancellablePromise<boolean> {
    return $Call.ByID(2635117723, config);
}
