// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NullInt64 represents an int64 that may be null.
 * NullInt64 implements the [Scanner] interface so
 * it can be used as a scan destination, similar to [NullString].
 */
export interface NullInt64 {
    "Int64": number;

    /**
     * Valid is true if Int64 is not NULL
     */
    "Valid": boolean;
}

/**
 * NullString represents a string that may be null.
 * NullString implements the [Scanner] interface so
 * it can be used as a scan destination:
 * 
 * 	var s NullString
 * 	err := db.QueryRow("SELECT name FROM foo WHERE id=?", id).Scan(&s)
 * 	...
 * 	if s.Valid {
 * 	   // use s.String
 * 	} else {
 * 	   // NULL value
 * 	}
 */
export interface NullString {
    "String": string;

    /**
     * Valid is true if String is not NULL
     */
    "Valid": boolean;
}
