// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export interface ColumnInfo {
    "name": string;
    "databaseType": string;
    "nullable": boolean;
    "defaultValue": string;
}

export interface ConnectionConfig {
    "ID": string;
    "Name": string;
    "Type": string;
    "Host": string;
    "Port": number;
    "User": string;
    "Password": string;
    "Database": string;
    "SSL": boolean;
    "SSHConfigID": number | null;
    "SSHConfig": SSHConfig | null;
    "InMemory": boolean;
    "ReadOnly": boolean;
    "Color": string;
}

export interface InspectTableInfo {
    "name": string;

    /**
     * TABLE, VIEW
     */
    "type": string;
    "database": string;
    "schema"?: string;
    "rows"?: number;
    "engine"?: string;
    "comment"?: string;
    "createdAt"?: string | null;
    "updatedAt"?: string | null;
}

export enum QueryExecutionType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    QueryExecutionExecute = 0,
    QueryExecutionFetchPaged = 1,
    QueryExecuteRefresh = 2,
    QueryExecutionClose = 3,
    QueryExecutionNavigate = 4,
};

export interface QueryInput {
    "query": string;
    "cursor": string;
    "type": QueryExecutionType;
    "pageSize": number;
    "page": number;
    "sortColumn"?: number;
    "sortDirection"?: string;
}

export interface QueryResult {
    "columns": ColumnInfo[] | null;
    "rows": (any[] | null)[] | null;
    "rowsAffected": number;
    "lastInsertId": number;
    "duration": time$0.Duration;
    "isQuery": boolean;
    "cursor": string;
    "hasMore": boolean;
    "startRow": number;
    "pageSize": number;
    "totalRows"?: number | null;
    "canNavigate": boolean;
}

export interface SSHConfig {
    "ID": number;
    "Name": string;
    "Host": string;
    "Port": number;
    "Username": string;
    "AuthMethod": string;
    "PrivateKey": string;
    "Passphrase": string;
    "Password": string;
}
