// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../engine/entities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function Connect(config: entities$0.ConnectionConfig): $CancellablePromise<boolean> {
    return $Call.ByID(2446242533, config);
}

export function DescribeTableEdit(table: entities$0.TableRef): $CancellablePromise<entities$0.TableEditInfo | null> {
    return $Call.ByID(1931031332, table);
}

export function Disconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(753429703, connID);
}

export function ExecuteQuery(queryInput: entities$0.QueryInput): $CancellablePromise<entities$0.QueryResult | null> {
    return $Call.ByID(940505008, queryInput);
}

export function GetActiveConnection(): $CancellablePromise<string> {
    return $Call.ByID(3424422817);
}

export function GetActiveConnectionObject(): $CancellablePromise<[types$0.Connection, boolean]> {
    return $Call.ByID(3293129022);
}

export function GetDDL(table: entities$0.TableRef): $CancellablePromise<string> {
    return $Call.ByID(1140029165, table);
}

export function GetQueryHistory(limit: number, since: string): $CancellablePromise<db$0.QueryHistoryEntity[] | null> {
    return $Call.ByID(1944907923, limit, since);
}

export function InspectDatabase(): $CancellablePromise<entities$0.InspectTableInfo[] | null> {
    return $Call.ByID(4019461670);
}

/**
 * InspectTableColumns is read-only metadata, including for views and read-only connections.
 */
export function InspectTableColumns(table: entities$0.TableRef): $CancellablePromise<entities$0.InspectColumnInfo[] | null> {
    return $Call.ByID(866663916, table);
}

export function PingConfig(config: entities$0.ConnectionConfig): $CancellablePromise<boolean> {
    return $Call.ByID(1404477927, config);
}

export function PingConnection(connID: string): $CancellablePromise<boolean> {
    return $Call.ByID(105455865, connID);
}

export function SaveAndConnect(config: entities$0.ConnectionConfig): $CancellablePromise<boolean> {
    return $Call.ByID(238343449, config);
}

export function SaveTableChanges(input: entities$0.TableChanges): $CancellablePromise<entities$0.TableSaveResult | null> {
    return $Call.ByID(1918929209, input);
}

export function TestSSHConnection(config: entities$0.SSHConfig): $CancellablePromise<boolean> {
    return $Call.ByID(210397393, config);
}
