// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";

export interface Connection {
    "id": number;
    "name": string;
    "driver": string;
    "host": string;
    "port": sql$0.NullInt64;
    "user": string;
    "password": string;
    "dbname": string;
    "pinned": boolean;
    "color": sql$0.NullString;
    "ssh_config_id": sql$0.NullInt64;
    "ssh_config": SSHConfig;
}

export interface SSHConfig {
    "id": number;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "auth_method": string;
    "private_key": sql$0.NullString;
    "passphrase": sql$0.NullString;
    "password": sql$0.NullString;
}
