// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface QueryHistoryEntity {
    "id": number;
    "connection_id": string;
    "databaseName": string;
    "query_text": string;
    "executed_at": number;
    "duration": number;
    "status": string;
}
