package pgxInspector

import (
	"context"
	manager "db-lens/internal/engine/connectionManager"
	"db-lens/internal/engine/entities"
	"fmt"
	"strings"
)

func (p *PostgresInspector) GetTableDDL(ctx context.Context, conn manager.Connection, table entities.TableRef) (string, error) {
	sqlConn, ok := conn.(manager.SQLConnection)
	if !ok {
		return "", fmt.Errorf("connection is not SQL")
	}
	quote := func(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }
	name := quote(table.Name)
	if table.Schema != "" {
		name = quote(table.Schema) + "." + name
	}
	var oid int64
	var kind, schema, relation string
	err := sqlConn.DB().QueryRowContext(ctx, `SELECT c.oid, c.relkind::text, n.nspname, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.oid = to_regclass($1)`, name).Scan(&oid, &kind, &schema, &relation)
	if err != nil {
		return "", fmt.Errorf("resolve table DDL: %w", err)
	}
	name = quote(schema) + "." + quote(relation)
	if kind == "v" || kind == "m" {
		var definition string
		if err := sqlConn.DB().QueryRowContext(ctx, `SELECT pg_get_viewdef($1::oid, true)`, oid).Scan(&definition); err != nil {
			return "", err
		}
		prefix := "CREATE VIEW "
		if kind == "m" {
			prefix = "CREATE MATERIALIZED VIEW "
		}
		return prefix + name + " AS\n" + strings.TrimRight(definition, "; \n") + ";", nil
	}
	if kind != "r" && kind != "p" {
		return "", fmt.Errorf("DDL is not supported for relation type %s", kind)
	}
	// Catalog deparsers preserve SQL expressions, identifier quoting and constraints.
	rows, err := sqlConn.DB().QueryContext(ctx, `SELECT quote_ident(a.attname), format_type(a.atttypid, a.atttypmod), a.attnotnull,
 COALESCE(pg_get_expr(d.adbin, d.adrelid), ''), COALESCE(to_jsonb(a)->>'attidentity', ''), COALESCE(to_jsonb(a)->>'attgenerated', ''),
 CASE WHEN a.attcollation <> t.typcollation THEN ' COLLATE ' || quote_ident(cn.nspname) || '.' || quote_ident(coll.collname) ELSE '' END
 FROM pg_attribute a JOIN pg_type t ON t.oid = a.atttypid
 LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
 LEFT JOIN pg_collation coll ON coll.oid = a.attcollation LEFT JOIN pg_namespace cn ON cn.oid = coll.collnamespace
 WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`, oid)
	if err != nil {
		return "", err
	}
	var definitions []string
	for rows.Next() {
		var column, typ, expression, identity, generated, collation string
		var required bool
		if err := rows.Scan(&column, &typ, &required, &expression, &identity, &generated, &collation); err != nil {
			rows.Close()
			return "", err
		}
		definition := "    " + column + " " + typ + collation
		switch {
		case identity == "a":
			definition += " GENERATED ALWAYS AS IDENTITY"
		case identity == "d":
			definition += " GENERATED BY DEFAULT AS IDENTITY"
		case generated != "":
			storage := "STORED"
			if generated == "v" {
				storage = "VIRTUAL"
			}
			definition += " GENERATED ALWAYS AS (" + expression + ") " + storage
		case expression != "":
			definition += " DEFAULT " + expression
		}
		if required {
			definition += " NOT NULL"
		}
		definitions = append(definitions, definition)
	}
	err = rows.Err()
	rows.Close()
	if err != nil {
		return "", err
	}
	constraints, err := sqlConn.DB().QueryContext(ctx, `SELECT quote_ident(conname), pg_get_constraintdef(oid, true) FROM pg_constraint WHERE conrelid = $1 AND contype IN ('p','u','f','c','x') ORDER BY conname`, oid)
	if err != nil {
		return "", err
	}
	for constraints.Next() {
		var constraint, definition string
		if err := constraints.Scan(&constraint, &definition); err != nil {
			constraints.Close()
			return "", err
		}
		definitions = append(definitions, "    CONSTRAINT "+constraint+" "+definition)
	}
	err = constraints.Err()
	constraints.Close()
	if err != nil {
		return "", err
	}
	ddl := "CREATE TABLE " + name + " (\n" + strings.Join(definitions, ",\n") + "\n)"
	if kind == "p" {
		var partition string
		if err := sqlConn.DB().QueryRowContext(ctx, `SELECT pg_get_partkeydef($1::oid)`, oid).Scan(&partition); err != nil {
			return "", err
		}
		ddl += " PARTITION BY " + partition
	}
	ddl += ";"
	indexes, err := sqlConn.DB().QueryContext(ctx, `SELECT pg_get_indexdef(i.indexrelid) FROM pg_index i WHERE i.indrelid = $1 AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid) ORDER BY i.indexrelid`, oid)
	if err != nil {
		return "", err
	}
	defer indexes.Close()
	for indexes.Next() {
		var definition string
		if err := indexes.Scan(&definition); err != nil {
			return "", err
		}
		ddl += "\n\n" + definition + ";"
	}
	return ddl, indexes.Err()
}
